import { chakra } from "@chakra-ui/react";
import Head from "next/head";
import { PropsWithChildren } from "react";
import Header from "./Header";

const PageWrapper = chakra("div", {
  baseStyle: {
    position: "relative",
    margin: "0 auto",
    display: "flex",
    flexFlow: "column",
    alignItems: "center",
    minHeight: "100%",
    px: ["24px", null, "48px"],
    pt: "10px",
    maxW: "768px",
  },
});

export const Page = ({ children }: PropsWithChildren<unknown>) => {
  return (
    <>
      <Head>
        <title>Lily's simming tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Header />
        {children}
      </PageWrapper>
    </>
  );
};
